### ISSUE TITLE
Update for Minecraft 1.14.X

### ISSUE THREAD

**Issue by Thaephos** [redstonekasi/serverping#2]
Hey there,

I wanted to have my custom server run without having the tablist show players that were in the server and I figured that this mod would help with that. Currently I'm unsure if this mod is able to do that, but just in case, I'm running into a few issues.

Firstly, the mod obviously didn't run right away because the versions do not match. I edited the .jar file to be able to accept minecraft 1.19.X and fabric 0.14.14. This didn't have any luck either.

Lastly, I tried changing the config file produced after it was populated to contain true for both statements, but also to no avail.

Any ideas why it might not be working, or if this mod won't even accomplish what I'm trying to do? If the case is that this mod isn't for what I want, then could you direct me to where I can find something like this that doesn't use Bukkit or Sprigot?

Thank you so much for the help!

**Comment by redstonekasi** [comment]
Sorry, it's a bit unclear as to what version you actually want this mod on, 1.14.x or 1.19.x?

**Comment by redstonekasi** [comment]
This is now resolved by 1.2.0 which supports all (Fabric-compatible) Minecraft versions.

https://github.com/redstonekasi/serverping/releases/tag/1.2.0
https://modrinth.com/mod/serverping/version/1.2.0
https://www.curseforge.com/minecraft/mc-mods/serverping/files/4392839
